# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(463, 428)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.papeldeparede = QtWidgets.QLabel(self.centralwidget)
        self.papeldeparede.setGeometry(QtCore.QRect(20, 20, 421, 371))
        self.papeldeparede.setStyleSheet("background-color: rgb(211, 196, 255);")
        self.papeldeparede.setText("")
        self.papeldeparede.setObjectName("papeldeparede")
        self.iconsenha = QtWidgets.QLabel(self.centralwidget)
        self.iconsenha.setGeometry(QtCore.QRect(110, 190, 47, 31))
        self.iconsenha.setStyleSheet("image: url(:/imgs/006-cadeado.png);")
        self.iconsenha.setText("")
        self.iconsenha.setObjectName("iconsenha")
        self.iconuser = QtWidgets.QLabel(self.centralwidget)
        self.iconuser.setGeometry(QtCore.QRect(110, 140, 51, 31))
        self.iconuser.setStyleSheet("image: url(:/imgs/001-do-utilizador.png);")
        self.iconuser.setText("")
        self.iconuser.setObjectName("iconuser")
        self.esqueceusenha = QtWidgets.QLabel(self.centralwidget)
        self.esqueceusenha.setGeometry(QtCore.QRect(40, 350, 101, 21))
        self.esqueceusenha.setObjectName("esqueceusenha")
        self.btnEntrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnEntrar.setGeometry(QtCore.QRect(130, 260, 91, 31))
        self.btnEntrar.setObjectName("btnEntrar")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(130, 40, 211, 71))
        self.titulo.setObjectName("titulo")
        self.leSenha = QtWidgets.QLineEdit(self.centralwidget)
        self.leSenha.setGeometry(QtCore.QRect(160, 190, 221, 21))
        self.leSenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.leSenha.setObjectName("leSenha")
        self.leUsuario = QtWidgets.QLineEdit(self.centralwidget)
        self.leUsuario.setGeometry(QtCore.QRect(160, 150, 221, 21))
        self.leUsuario.setInputMask("")
        self.leUsuario.setText("")
        self.leUsuario.setObjectName("leUsuario")
        self.btnSair = QtWidgets.QPushButton(self.centralwidget)
        self.btnSair.setGeometry(QtCore.QRect(270, 260, 91, 31))
        self.btnSair.setObjectName("btnSair")
        self.btnCadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCadastrar.setGeometry(QtCore.QRect(290, 330, 101, 41))
        self.btnCadastrar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"image: url(:/imgs/003-adicionar-usuario.png);")
        self.btnCadastrar.setText("")
        self.btnCadastrar.setObjectName("btnCadastrar")
        self.errou = QtWidgets.QLabel(self.centralwidget)
        self.errou.setGeometry(QtCore.QRect(150, 220, 221, 31))
        self.errou.setText("")
        self.errou.setObjectName("errou")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 463, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionCliente = QtWidgets.QAction(MainWindow)
        self.actionCliente.setObjectName("actionCliente")
        self.actionSistema = QtWidgets.QAction(MainWindow)
        self.actionSistema.setObjectName("actionSistema")
        self.actionVAmos = QtWidgets.QAction(MainWindow)
        self.actionVAmos.setObjectName("actionVAmos")
        self.actionLe = QtWidgets.QAction(MainWindow)
        self.actionLe.setObjectName("actionLe")
        self.actionSD = QtWidgets.QAction(MainWindow)
        self.actionSD.setObjectName("actionSD")
        self.actionSJDKJWI = QtWidgets.QAction(MainWindow)
        self.actionSJDKJWI.setObjectName("actionSJDKJWI")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.esqueceusenha.setText(_translate("MainWindow", "Esqueceu Senha?"))
        self.btnEntrar.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Entrar no Sistema</span></p></body></html>"))
        self.btnEntrar.setText(_translate("MainWindow", "Entrar"))
        self.titulo.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Tela Login</span></p></body></html>"))
        self.leSenha.setToolTip(_translate("MainWindow", "<html><head/><body><p>Digite senha</p></body></html>"))
        self.leSenha.setPlaceholderText(_translate("MainWindow", "Digite Senha"))
        self.leUsuario.setToolTip(_translate("MainWindow", "<html><head/><body><p>Digite login</p></body></html>"))
        self.leUsuario.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Digite login</p></body></html>"))
        self.leUsuario.setPlaceholderText(_translate("MainWindow", "Digite Usuário"))
        self.btnSair.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Fechar</span></p></body></html>"))
        self.btnSair.setText(_translate("MainWindow", "Sair"))
        self.btnCadastrar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Cadastrar Usuário</p></body></html>"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionCliente.setText(_translate("MainWindow", "Cliente"))
        self.actionSistema.setText(_translate("MainWindow", "Sistema"))
        self.actionVAmos.setText(_translate("MainWindow", "VAmos"))
        self.actionLe.setText(_translate("MainWindow", "Le"))
        self.actionSD.setText(_translate("MainWindow", "SD"))
        self.actionSJDKJWI.setText(_translate("MainWindow", "SJDKJWI"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = UI_login()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
